name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

  flutter_native_splash: ^2.2.4

flutter_native_splash:
  ios: true
  web: true
  android: true
  background_image: "assets/splashscreen.jpg"

  image: "assets/splashscreen.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/splashscreen.jpg
#     - assets/images/derrota.jpg
#     - assets/images/victoria.jpg
    - assets/images/derrota.svg
    - assets/images/victoria.svg


